/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author kachu
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final Controlador controlador;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Controlador c) {
        
        initComponents();
        this.controlador = c ;
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        /*ImageIcon img = new ImageIcon("src/imagen/img.png") ;
        Icon icono = new ImageIcon(img.getImage().getScaledInstance(labelImg.getWidth(), labelImg.getWidth(), Image.SCALE_DEFAULT)) ;
        labelImg.setIcon(icono);
        this.repaint();*/
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPaciente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHisCli = new javax.swing.JButton();
        btnTur = new javax.swing.JButton();
        btnMed = new javax.swing.JButton();
        btnEspe = new javax.swing.JButton();
        labelImg = new javax.swing.JLabel();
        labelImg2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/paci.png"))); // NOI18N
        btnPaciente.setText("PACIENTES");
        btnPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPaciente.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 220, 90));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("VENTANA PRINCIPAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnHisCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/hiscli.png"))); // NOI18N
        btnHisCli.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnHisCli.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnHisCli.setLabel("HISTORIAS CLINICAS");
        btnHisCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHisCliActionPerformed(evt);
            }
        });
        getContentPane().add(btnHisCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 100));

        btnTur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/tur.png"))); // NOI18N
        btnTur.setText("TURNOS");
        btnTur.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        btnTur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTurActionPerformed(evt);
            }
        });
        getContentPane().add(btnTur, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 210, 90));

        btnMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/medic.png"))); // NOI18N
        btnMed.setText("MEDICOS");
        btnMed.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedActionPerformed(evt);
            }
        });
        getContentPane().add(btnMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 210, 100));

        btnEspe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/espe.png"))); // NOI18N
        btnEspe.setText("ESPECIALIDADES");
        btnEspe.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnEspe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEspe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 220, 90));

        labelImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/img.png"))); // NOI18N
        getContentPane().add(labelImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 110, -1));

        labelImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/img2.png"))); // NOI18N
        getContentPane().add(labelImg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 60, 60));

        label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/img3.png"))); // NOI18N
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        try {
            
            this.dispose();
            VistaPaciente vp = new VistaPaciente(controlador,this ) ;
           
        } catch (Exception e) {
            System.out.println("ERROR papa");
        }
        
        
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnHisCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHisCliActionPerformed
        try {
            
            this.dispose();
            VistaHistoriaClinica vhc = new VistaHistoriaClinica(controlador,this) ;
           
        } catch (Exception e) {
            System.out.println("ERROR papa");
        }
    }//GEN-LAST:event_btnHisCliActionPerformed

    private void btnTurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTurActionPerformed
        this.dispose();
        VistaTurno vt = new VistaTurno(controlador, this) ;
    }//GEN-LAST:event_btnTurActionPerformed

    private void btnEspeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspeActionPerformed
        try {
            
            this.dispose();
            VistaEspecialidad ve = new VistaEspecialidad(controlador,this) ;
           
        } catch (Exception e) {
            System.out.println("ERROR papa");
        }
    }//GEN-LAST:event_btnEspeActionPerformed

    private void btnMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedActionPerformed
        try {
            
            this.dispose();
            VistaMedico vm = new VistaMedico(controlador,this) ;
           
        } catch (Exception e) {
            System.out.println("ERROR papa");
        }
    }//GEN-LAST:event_btnMedActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEspe;
    private javax.swing.JButton btnHisCli;
    private javax.swing.JButton btnMed;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnTur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel labelImg;
    private javax.swing.JLabel labelImg2;
    // End of variables declaration//GEN-END:variables
}
