/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JCalendar;
import controlador.Controlador;
import datechooser.beans.DateChooserCombo;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import modelo.*;

/**
 *
 * @author kachu
 */
public class VistaPaciente extends javax.swing.JFrame {

    private final Controlador controlador;
    private JFrame previo;

    /**
     * Creates new form vistaPaciente
     */
    public VistaPaciente(Controlador c, JFrame p) {

        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.controlador = c;
        this.previo = p;
        bloquear();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombrePac = new javax.swing.JTextField();
        txtApellidoPac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPaciente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHisMed = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDniPac = new javax.swing.JFormattedTextField();
        txtBus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(665, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lista1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 369, 257));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel2.setText("Apellido");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel3.setText("DNI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtNombrePac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePacKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombrePac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 138, -1));

        txtApellidoPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPacKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellidoPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 138, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setText("PACIENTES");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 221, 43));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        btnPaciente.setText("Ver Pacientes");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jLabel5.setText("Fecha de Nac.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel6.setText("Nr. Tel");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });
        jPanel1.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 150, -1));

        jLabel7.setText("Historial Medico");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        jPanel1.add(txtHisMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 150, 69));
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 150, -1));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, -1, -1));

        try {
            txtDniPac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDniPac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniPacActionPerformed(evt);
            }
        });
        jPanel1.add(txtDniPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 138, -1));
        jPanel1.add(txtBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        try {
            this.lista1.setListData(this.controlador.listarPacientes().toArray());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtNombrePac.getText().isEmpty() || txtApellidoPac.getText().isEmpty() || txtDniPac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cargue los campos correspondientes");
        } else {
            if (!this.lista1.isSelectionEmpty()) {
                Paciente paciente = (Paciente) lista1.getSelectedValue();
                String nombre = txtNombrePac.getText();
                String apellido = txtApellidoPac.getText();
                Date fecha = txtDate.getDate();
                int tel = Integer.parseInt(txtTel.getText());
                String hisMed = txtHisMed.getText();
                controlador.modificacionPaciente(paciente, nombre, apellido, fecha, tel, hisMed);
            } else {
                int dni = Integer.parseInt(this.txtDniPac.getText());
                String nombre = this.txtNombrePac.getText();
                String apellido = this.txtApellidoPac.getText();
                JCalendar jc = new JCalendar();
                Date fecha = jc.getDate();
                int numTel = Integer.parseInt(txtTel.getText());
                String hisMedic = txtHisMed.getText();
                this.controlador.altaPaciente(dni, nombre, apellido, fecha, numTel, hisMedic);
                JOptionPane.showMessageDialog(null, "Se cargo con exito!");
                this.txtNombrePac.setText("");
                this.txtApellidoPac.setText("");
                this.txtDniPac.setText("");
                this.txtNombrePac.requestFocus();
            }
            recargarPaciente();
            this.btnSave.setEnabled(false);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void lista1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista1ValueChanged
        try {
            if (!lista1.isSelectionEmpty()) {
                
                this.btnSave.setEnabled(true);
                Paciente paciente = (Paciente) this.lista1.getSelectedValue();
                this.txtNombrePac.setText(paciente.getNombre());
                this.txtApellidoPac.setText(paciente.getApellido());
                this.txtDniPac.setText(Integer.toString(paciente.getDni()));
                this.txtDate.setDate(paciente.getFechaNac());
                this.txtTel.setText(Integer.toString(paciente.getNumTel()));
                this.txtHisMed.setText(paciente.getHistorialMedico());
                this.txtDniPac.setEditable(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }

    }//GEN-LAST:event_lista1ValueChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (this.txtBus.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete campo buscar");
        } else {
            this.lista1.setListData(this.controlador.listarPacientes().toArray());
            String pac = this.txtBus.getText();
            int bus = this.lista1.getNextMatch(pac, 0, Position.Bias.Forward);
            this.lista1.setSelectedIndex(bus);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        recargarPaciente();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.previo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.previo.setVisible(true);
        this.previo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        bloquear();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDniPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniPacActionPerformed

    private void txtNombrePacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePacKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) ) {

        } else {
            evt.consume();
            //getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombrePacKeyTyped

    private void txtApellidoPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPacKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) ) {

        } else {
            evt.consume();
            //getToolkit().beep();
        }
    }//GEN-LAST:event_txtApellidoPacKeyTyped

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        char car = evt.getKeyChar();
        if (Character.isDigit(car) ) {

        } else {
            evt.consume();
            //getToolkit().beep();
        }
    }//GEN-LAST:event_txtTelKeyTyped

    private void bloquear() {
        this.txtApellidoPac.setEditable(false);
        this.txtNombrePac.setEditable(false);
        this.txtTel.setEditable(false);
        this.txtHisMed.setEditable(false);
        this.txtDniPac.setEditable(false);
        this.txtDate.setEnabled(false);
        this.btnSave.setEnabled(false);

    }

    private void recargarPaciente() {
        this.lista1.clearSelection();
        //this.lista1.setListData(this.controlador.listarPacientes().toArray());
        this.txtNombrePac.setText("");
        this.txtApellidoPac.setText("");
        this.txtDniPac.setText("");
        this.txtDate.setCalendar(null);
        this.txtTel.setText("");
        this.txtHisMed.setText("");
        this.btnSave.setEnabled(true);
        this.txtDniPac.setEditable(true);
        this.txtApellidoPac.setEditable(true);
        this.txtNombrePac.setEditable(true);
        this.txtTel.setEditable(true);
        this.txtHisMed.setEditable(true);
        this.txtDniPac.setEditable(true);
        this.txtDate.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista1;
    private javax.swing.JTextField txtApellidoPac;
    private javax.swing.JTextField txtBus;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JFormattedTextField txtDniPac;
    private javax.swing.JTextField txtHisMed;
    private javax.swing.JTextField txtNombrePac;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
