/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JCalendar;
import controlador.Controlador;
import datechooser.beans.DateChooserCombo;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.Position;
import modelo.*;

/**
 *
 * @author kachu
 */
public class VistaPaciente extends javax.swing.JFrame {

    private final Controlador controlador;
    private JFrame previo;

    /**
     * Creates new form vistaPaciente
     */
    public VistaPaciente(Controlador c, JFrame p) {

        initComponents();
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.controlador = c;
        this.previo = p;
        this.txtDate.setDate(new Date(100, 1, 1));
        recargarLista();
        bloquear();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombrePac = new javax.swing.JTextField();
        txtApellidoPac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPaciente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHisMed = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();
        btnNuevo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtDniPac = new javax.swing.JFormattedTextField();
        txtBus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setSize(new java.awt.Dimension(665, 450));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lista1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lista1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lista1);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("DNI");

        txtNombrePac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombrePacKeyTyped(evt);
            }
        });

        txtApellidoPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPacActionPerformed(evt);
            }
        });
        txtApellidoPac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPacKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setText("PACIENTES");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPaciente.setText("Ver Pacientes");
        btnPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de Nac.");

        jLabel6.setText("Nr. Tel");

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });

        jLabel7.setText("Historial Medico");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        try {
            txtDniPac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDniPac.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDniPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniPacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtHisMed, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(txtTel)
                                    .addComponent(txtDniPac, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtNombrePac)
                                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(btnPaciente))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnNuevo)
                        .addGap(127, 127, 127)
                        .addComponent(btnSave)
                        .addGap(129, 129, 129)
                        .addComponent(btnCancelar)
                        .addGap(155, 155, 155)
                        .addComponent(btnSalir)))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addGap(34, 34, 34)
                        .addComponent(txtBus, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnBuscar)
                                .addComponent(txtBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnPaciente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombrePac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDniPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHisMed, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo)
                    .addComponent(btnSave)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalir)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacienteActionPerformed
        try {
            this.lista1.setListData(this.controlador.listarPacientes().toArray());
            bloquear();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnPacienteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (txtNombrePac.getText().isEmpty() || txtApellidoPac.getText().isEmpty() || txtDniPac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cargue los campos correspondientes");
        } else {
            if (!this.lista1.isSelectionEmpty()) {
                Paciente paciente = (Paciente) lista1.getSelectedValue();
                String nombre = txtNombrePac.getText();
                String apellido = txtApellidoPac.getText();
                Date fecha = txtDate.getDate();
                int tel = Integer.parseInt(txtTel.getText());
                String hisMed = txtHisMed.getText();
                controlador.modificacionPaciente(paciente, nombre, apellido, fecha, tel, hisMed);
                recargarLista();
                recargarPaciente();
            } else {
                int dni = 0;
                try {
                    dni = Integer.parseInt(this.txtDniPac.getText());
                }catch (Exception e) {
                }
                String nombre = this.txtNombrePac.getText();
                String apellido = this.txtApellidoPac.getText();
                JCalendar jc = new JCalendar();
                Date fecha = jc.getDate();
                int numTel = Integer.parseInt(txtTel.getText());
                String hisMedic = txtHisMed.getText();
                if (dni !=0){
                    this.controlador.altaPaciente(dni, nombre, apellido, fecha, numTel, hisMedic);
                    JOptionPane.showMessageDialog(null, "Se cargo con exito!");
                    this.txtNombrePac.setText("");
                    this.txtApellidoPac.setText("");
                    this.txtDniPac.setText("");
                    this.txtNombrePac.requestFocus();
                    recargarPaciente();
                    recargarLista();
                }
                else{
                    JOptionPane.showMessageDialog(null, "por favor cargue bien");
                }
            }
            bloquear();
            
            this.btnSave.setEnabled(false);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void lista1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lista1ValueChanged
        try {
            if (!lista1.isSelectionEmpty()) {
                
                this.btnSave.setEnabled(true);
                Paciente paciente = (Paciente) this.lista1.getSelectedValue();
                this.txtNombrePac.setText(paciente.getNombre());
                this.txtApellidoPac.setText(paciente.getApellido());
                this.txtDniPac.setText(Integer.toString(paciente.getDni()));
                this.txtDate.setDate(paciente.getFechaNac());
                this.txtTel.setText(Integer.toString(paciente.getNumTel()));
                this.txtHisMed.setText(paciente.getHistorialMedico());
                this.txtDniPac.setEditable(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }

    }//GEN-LAST:event_lista1ValueChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (this.txtBus.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete campo buscar");
        } else {
            this.lista1.setListData(this.controlador.listarPacientes().toArray());
            String pac = this.txtBus.getText();
            int bus = this.lista1.getNextMatch(pac, 0, Position.Bias.Forward);
            this.lista1.setSelectedIndex(bus);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        recargarPaciente();

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.previo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.previo.setVisible(true);
        this.previo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        bloquear();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDniPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniPacActionPerformed

    private void txtNombrePacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePacKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isSpaceChar(car)) {

        } else {
            evt.consume();
            //getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombrePacKeyTyped

    private void txtApellidoPacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPacKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isSpaceChar(car)) {

        } else {
            evt.consume();
            //getToolkit().beep();
        }
    }//GEN-LAST:event_txtApellidoPacKeyTyped

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        char car = evt.getKeyChar();
        if (Character.isDigit(car) ) {

        } else {
            evt.consume();
            //getToolkit().beep();
        }
    }//GEN-LAST:event_txtTelKeyTyped

    private void txtApellidoPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPacActionPerformed

    private void bloquear() {
        this.txtApellidoPac.setEditable(false);
        this.txtNombrePac.setEditable(false);
        this.txtTel.setEditable(false);
        this.txtHisMed.setEditable(false);
        this.txtDniPac.setEditable(false);
        this.txtDate.setEnabled(false);
        this.btnSave.setEnabled(false);
        

    }
    private void recargarLista(){
        this.lista1.setListData(this.controlador.listarPacientes().toArray());
    }
    private void recargarPaciente() {
        if (!lista1.isSelectionEmpty()){
            this.lista1.clearSelection();
        }
        
        //this.lista1.setListData(this.controlador.listarPacientes().toArray());
        this.txtNombrePac.setText("");
        this.txtApellidoPac.setText("");
        this.txtDniPac.setText("");
        //this.txtDate.setCalendar(null);
        this.txtTel.setText("");
        this.txtHisMed.setText("");
        this.btnSave.setEnabled(true);
        this.txtDniPac.setEditable(true);
        this.txtApellidoPac.setEditable(true);
        this.txtNombrePac.setEditable(true);
        this.txtTel.setEditable(true);
        this.txtHisMed.setEditable(true);
        this.txtDniPac.setEditable(true);
        this.txtDate.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnPaciente;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lista1;
    private javax.swing.JTextField txtApellidoPac;
    private javax.swing.JTextField txtBus;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JFormattedTextField txtDniPac;
    private javax.swing.JTextField txtHisMed;
    private javax.swing.JTextField txtNombrePac;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
