/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Especialidad;
import modelo.Medico;

/**
 *
 * @author potoc
 */
public class VistaMedico extends javax.swing.JFrame {
    
    private final Controlador controlador;
    private JFrame previo ;
    
    /**
     * Creates new form VistaMedico
     */
    public VistaMedico(Controlador c, JFrame p) {
        initComponents();
        this.controlador = c;
        this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null) ;
        this.previo =  p ;
        DefaultComboBoxModel eCombo = new DefaultComboBoxModel(this.controlador.listarEspecialidades().toArray());
        this.comboespe.setModel(eCombo);
        recargarMedi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMat = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaMedico = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVer = new javax.swing.JButton();
        txtTel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        comboespe = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        btnRecargaMed = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtMat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMatKeyTyped(evt);
            }
        });

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        ListaMedico.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaMedicoValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(ListaMedico);

        jLabel1.setText("Matricula");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        btnVer.setText("Medicos");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelKeyTyped(evt);
            }
        });

        jLabel4.setText("NrTel");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel5.setText("MEDICOS");

        comboespe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboespeActionPerformed(evt);
            }
        });

        jLabel6.setText("Especialidad");

        btnRecargaMed.setText("Nuevo");
        btnRecargaMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargaMedActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(comboespe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRecargaMed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVer)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(1, 1, 1)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(5, 5, 5)
                        .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboespe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar)
                    .addComponent(btnVer)
                    .addComponent(btnRecargaMed)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        
        try {
            recargarMedi();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error1");
        }
    }//GEN-LAST:event_btnVerActionPerformed

    private void ListaMedicoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaMedicoValueChanged
        try {
            if(!this.ListaMedico.isSelectionEmpty()){
            Medico medicoChang = (Medico) this.ListaMedico.getSelectedValue();
            
            txtMat.setText(Integer.toString(medicoChang.getNrMatricula()));
        
            txtNombre.setText(medicoChang.getNombre());
        
            txtApellido.setText(medicoChang.getApellido());
        
            txtTel.setText(Integer.toString(medicoChang.getNrTel()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error");
        }
 
        
    }//GEN-LAST:event_ListaMedicoValueChanged

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        

            if (this.txtMat.getText().isEmpty() || this.txtApellido.getText().isEmpty() || this.txtNombre.getText().isEmpty() || this.txtTel.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tiene que completar todos los campos porfavor!");
            }
            else{
                
                if (!this.ListaMedico.isSelectionEmpty()) {
                    Medico medico = (Medico) this.ListaMedico.getSelectedValue();
            
                    //int nrMat = Integer.parseInt(txtMat.getText()); //lo que esta dentro del txtMat lo transformamos en integer
        
                    String nombre = txtNombre.getText();
        
                    String apellido = txtApellido.getText();
        
                    int nrTel = Integer.parseInt(txtTel.getText());
            
                    Especialidad espe = (Especialidad) comboespe.getSelectedItem();
            
                    this.controlador.modificarMedico(medico, nombre, apellido, nrTel, espe);
            
                    JOptionPane.showMessageDialog(null, "Se cargo");
            
                } else {
                    int nrMat = Integer.parseInt(txtMat.getText());//lo que esta dentro del txtMat lo transformamos en integer
        
                    List <Medico> medi =  controlador.listarMedico();
                    boolean existe = false;
                    int i = 0 ;
                    while ((existe != true) && (i < medi.size())){
                        if (medi.get(i).getNrMatricula() == nrMat ) {
                            existe = true;
                        } 
                        i++;  
                    }
                    if (existe == true){
                        JOptionPane.showMessageDialog(null, "Ya exite el numero de matricula!!");
                        limpiar();
                    }      
                    else {
                        String nombre = txtNombre.getText();
        
                        String apellido = txtApellido.getText();
        
                        int nrTel = Integer.parseInt(txtTel.getText());

                        Especialidad espe = (Especialidad) comboespe.getSelectedItem();
        
                        this.controlador.altaMedico(nrMat, nombre, apellido, nrTel, espe);
        
                        JOptionPane.showMessageDialog(null, "Se cargo");
                    }
                }
            }
        
            
        recargarMedi();                                     

    }//GEN-LAST:event_btnCargarActionPerformed

    private void comboespeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboespeActionPerformed
        
    }//GEN-LAST:event_comboespeActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        //char car = evt.getKeyChar();
        //if (Character.isLetter(car)){
            
        //}
        //else{
        //    evt.consume();
        //    getToolkit().beep();
        //}
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtMatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMatKeyTyped
        char car = evt.getKeyChar();
        if (Character.isDigit(car)){
            
        }
        else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtMatKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        /*char car = evt.getKeyChar();
        if (Character.isLetter(car)){
            
        }
        else{
            evt.consume();
            getToolkit().beep();
        }*/
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyTyped
        char car = evt.getKeyChar();
        if (Character.isDigit(car)){
            
        }
        else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtTelKeyTyped

    
    private void btnRecargaMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargaMedActionPerformed
          this.ListaMedico.clearSelection();
          this.txtMat.setText("");
          this.txtNombre.setText("");
          this.txtApellido.setText("");
          this.txtTel.setText("");
          desbloquear();
    }//GEN-LAST:event_btnRecargaMedActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.previo.setVisible(true);
        this.previo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.previo.setVisible(true);
        this.previo.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void desbloquear () {
        this.txtMat.setEditable(true);
        this.txtNombre.setEditable(true);
        this.txtApellido.setEditable(true);
        this.txtTel.setEditable(true);
    }
    
    private void limpiar () {
          this.txtMat.setText("");
          this.txtNombre.setText("");
          this.txtApellido.setText("");
          this.txtTel.setText("");
    }
    
    private void recargarMedi () {
        this.ListaMedico.setListData(this.controlador.listarMedico().toArray());

        
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaMedico;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnRecargaMed;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox comboespe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtMat;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
